version: '3.7'

services:
  postgresql:
    image: postgres:9.5-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  upsp-api:
    build:
      context: .
      target: "upsp"
    restart: always
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    image: upsp-api:latest
    container_name: "upsp-api"
    command: "/upsp -p postgres://postgres:postgres@postgresql:5432/postgres?sslmode=disable"
